### ISSUE TITLE
Changing the Player model disables the vr manager script and moves it to my scene (SOLVED)

### ISSUE THREAD

**Issue by SuperskillVR** [fchb1239/PhotonVR#1]
How can I use my own model with it? I can't change it without it not working for some reason

**Comment by SuperskillVR** [comment]
I fixed this by putting my models head and hands mesh renderer into the vr player script in the colour objects dropdown

**Comment by fchb1239** [comment]
Yes! That’s the solution, I’m aware of the issue and I will be fixing it (so it won’t error) in a new release soon along with some other things
