### ISSUE TITLE
i need a fix

### ISSUE THREAD

**Issue by Joseph8402** [fchb1239/PhotonVR#12]
can you fix the error Error while saving Prefab: 'Assets/Resources/PhotonVR/Player.prefab'. You are trying to save a Prefab that contains the script '', which does not derive from MonoBehaviour. This is not allowed.
Please change the script to derive from MonoBehaviour or remove it from the GameObject 'ObjectNameHere'.

**Comment by fchb1239** [comment]
I am unaware of that issue, try re-importing the player.cs script

**Comment by Joseph8402** [comment]
ok i will try that

**Comment by Joseph8402** [comment]
it didnt do anything just made it impossible for it to work

**Comment by fchb1239** [comment]
This is strange, try importing the package in a separate project and see if it works there.

**Comment by Joseph8402** [comment]
ok but the impossible to work is for every script even before that

**Comment by Joseph8402** [comment]
and it does work in other projects i will just change the project for my game if i get my game i will say and will close it

**Comment by Joseph8402** [comment]
well im gonna update unity to try and fix

**Comment by Joseph8402** [comment]
it is fixed
