### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Memerguygoogle** [fchb1239/PhotonVR#14]
How can I make it so that PhotonVRManager doesn't go into DDOL? I already removed the DontDestroyOnLoad(gameObject);

**Comment by fchb1239** [comment]
Then it should go DDOL, may I ask why though? When you switch scenes you'd have to reconnect to Photon.

I'd recommend having a starting scene with everything required for your game to function (Rig, PhotonVR, managers, etc...) then only visit that scene once.

**Comment by Memerguygoogle** [comment]
yeah, but i need a different photonvrmanager, because when i scene change the photonvrmanager wont know what my head, lefthand, and righthand is

**Comment by Memerguygoogle** [comment]
due to a new gorilla rig

**Comment by Memerguygoogle** [comment]
made a script to fix it

**Comment by fchb1239** [comment]
Ok great
