### ISSUE TITLE
this is more of me asking for a feature then a issue 

### ISSUE THREAD

**Issue by CoolPuppyKid** [fchb1239/PhotonVR#18]
i want you to add cosmetic slots that dont save so like if you want to give the player a cosmetic that wont save

**Comment by MaxNiftyNine** [comment]
im not the owner but ill add it to my pull request

**Comment by MaxNiftyNine** [comment]
You know what I realized is that this is not something that photonvr should have built in, just make a script that saves the current cosmetic before equipping a new one, then on startup restores the original

I will not add this to my pull request

**Comment by eight-eighty-eight** [comment]
DAMN BRO GOT ROASTED
