### ISSUE TITLE
Debug.Log stuff

### ISSUE THREAD

**Issue by MaxNiftyNine** [fchb1239/PhotonVR#19]
there's a bunch of things in the current update that kinda just spam debug.log on update, please fix next update, also sharing the photon code in debug.log also is kinda a security problem

**Comment by MaxNiftyNine** [comment]
I saw your reply to an old pull request that ansers this

**Comment by fchb1239** [comment]
I don't spam anything on update

**Comment by MaxNiftyNine** [comment]
Line 90 photonvr player, it's not update but still a bit annoying

**Comment by fchb1239** [comment]
Oh that, yeah that was meant to be removed on release
