### ISSUE TITLE
photonvr

### ISSUE THREAD

**Issue by vortexVR58** [fchb1239/PhotonVR#2]
when i import it in my unity project in Resorces its not the only the photon package so how do i make my player models

**Comment by fchb1239** [comment]
What

**Comment by TheScruffyKat** [comment]
average conversation on github

**Comment by Cricket-Programming** [comment]
vortexVR58, please don't put issues here to ge t help. This place is for actual issues.

**Comment by fchb1239** [comment]
I'll just close this as it seems it's finished?
