### ISSUE TITLE
Please read!

### ISSUE THREAD

**Issue by bubzilla** [fchb1239/PhotonVR#30]
I want to know how I could implement a local player and if photon fusion works uwus?

**Comment by bubzilla** [comment]
For context I mean local player like a local rig with cosmetics.

**Comment by ghost** [comment]
You know there is a package called fusion vr made by the creator of photon vr.

**Comment by fchb1239** [comment]
That is a feature you need to implement yourself.
However you can make a Photon room in OfflineMode, which essentially means you're in a disconnected room, but everything Photon related works like you are in a room.
This includes the player rig.

**Comment by Phoenix9867games** [comment]
Could you elaborate more on how to do it? Cause when I tried doing it something broke. And the documentation is not that clear (at least to me)

**Comment by fchb1239** [comment]
Hi 👋 

You are commenting on the wrong repository, please go to FusionVR repository instead.

Thanks!

**Comment by ghost** [comment]
Well oki
