### ISSUE TITLE
Photon VR attempts to find a Fusion Id by default

### ISSUE THREAD

**Issue by lovelyylayna** [fchb1239/PhotonVR#48]
Digging through the code either this is an mistake or intentional but Photon VR's CheckDefaultValues function attempts to grab the Photon Fusion instead of the realtime id.

**Comment by Mast3rM0ds** [comment]
thats true idk if its a miss type but here u can see AppId = PhotonNetwork.PhotonServerSettings.AppSettings.AppIdFusion; it trys to sets the appid to the fusion appid and that aint good but if u want to fix it then just change it to AppId = PhotonNetwork.PhotonServerSettings.AppSettings.AppIdRealtime; im sure

**Comment by lovelyylayna** [comment]
Yeah that is how you fix it. I was only marking it as an issue due to the fact it is a Photon Pun or Realtime package not a Fusion package.

Thanks,
Avery

**Comment by fchb1239** [comment]
Woops, that's my mistake. I'll fix it eventually

**Comment by lovelyylayna** [comment]
> Woops, that's my mistake. I'll fix it eventually

Haha it happens.
