### ISSUE TITLE
Insanely Slow Performance

### ISSUE THREAD

**Issue by radekmotyka** [fchb1239/PhotonVR#6]
When I export for Quest It's like 5 second behind everything and when I preview in unity its just fine.

**Comment by fchb1239** [comment]
There could be multiple causes for this, and even then - this isn't Photon VRs fault.

Photon VR is simply an extension to Photon to make it integrate with VR more easily.

Please keep in mind there are servers that have to handle the player data, and if the region isn't set to be near you, you will have higher ping.

Try setting the region to something closer to you.
