### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zoomzoom1001000** [fchb1239/PhotonVR#7]
Assets\Resources\PhotonVR\Scripts\Player\PhotonVRPlayer.cs(83,26): error CS1061: 'TextMeshPro' does not contain a definition for 'text' and no accessible extension method 'text' accepting a first argument of type 'TextMeshPro' could be found (are you missing a using directive or an assembly reference?

**Comment by fchb1239** [comment]
As stated in the documentation, you must import TextMeshPro.
