### ISSUE TITLE
Changing Recorder Sampling Rate in PhotonVRVoice Prefab creates errors building player

### ISSUE THREAD

**Issue by Cricket-Programming** [fchb1239/PhotonVR#9]
I have tested this issue in unity 2021 and 2022.
The issue as shown in the console of the picture happens when I change the recorder sampling rate in my photonvrvoice prefab that I dragged into the hierarchy.
<img width="1009" alt="Screenshot 2023-05-11 174912" src="https://github.com/fchb1239/PhotonVR/assets/105169355/c376f283-d5b9-4111-87cf-7ff9748c746d">

**Comment by fchb1239** [comment]
Weird, I don't think it's the sampling rate.

I've seen the error before but I'm not sure what's going on. I'd recommend to just reinstall Photon VR (and then skip the Player as you don't want to lose that)

**Comment by Cricket-Programming** [comment]
Thanks for the suggestion fchb1239. I found that just deleting the prefab from the scene, putting a new one back in, and then restart the unity project fixes the error. Also, thanks for this amazing library. It is wonderful. (

**Comment by Cricket-Programming** [comment]
I tested this issue in another brand new project and the changing the sampling rate doesn't affect the build's success! So, this error is actually not something to do with photonvrmanager and has just had something to do with that project. Because it's not actually an issue, I'm going to close it.
